### ISSUE TITLE
Disable hash adding to certain file

### ISSUE THREAD

**Issue by rapidfixer** [sindresorhus/gulp-rev#111]
I've got certain file with filename that should be frozen after gulp-rev.
What should i do to tell rev not to add hash to this file?
Thanks.

**Comment by sindresorhus** [comment]
You can filter it out with gulp-filter.

**Comment by borisceranic** [comment]
@rapidfixer, you should use other means of removing the file from `gulp-rev`'s input, for example using [gulp-filter](https://github.com/sindresorhus/gulp-filter), like this:

```javascript
var rev = require('gulp-rev');
var filter = require('gulp-filter');

var skipFilesFilter = filter(function(file){
    return /skipthisfile\.css$/
        .test(file.path);
});

gulp.src('static-files/**/*')
    // ...transformations...
    .pipe(skipFilesFilter)
    .pipe(rev())
    .pipe(skipFilesFilter.restore())
    // ...some more transformations...
    .pipe(gulp.dest('output-dir'))
    // ...generate and save rev-manifest.json...
```

Of course, you don't have to invoke same filter when calling `gulp-rev-manifest`, since the removed file is not kept in the list of revisioned files.
