### ISSUE TITLE
Garbled manifest file

### ISSUE THREAD

**Issue by austerus** [sindresorhus/gulp-rev#115]
Hello,

I am trying to use gulp-rev to have a cache busting system alongside a Symfony2 application, but when I try to use it my gulp file, it always results in some very random contents of the manifest file.

How it looks like in gulp:

``` 
function addCss(paths, output) {
    gulp.src(paths)
        .pipe(plugins.buffer())
        .pipe(plugins.rename(output))
        .pipe(plugins.rev())
        .pipe(gulp.dest(config.webFolder))
        .pipe(plugins.rev.manifest('dist/rev-manifest.json', {base: process.cwd()+'/dist', merge: true}))
        .pipe(gulp.dest('dist'));
}
```

Task where this is called:

```
gulp.task('css-all', function() {
    addCss('CoreBundle/Resources/css/inspinia/animate.css', 'css/inspinia/animate.css');
    addCss('CoreBundle/Resources/css/bootstrap.css', 'css/bootstrap.css');
    addCss('CoreBundle/Resources/css/deploy.css', 'css/deploy.css');
})
```

Resulting manifest file:
```
{
  "css/core/bootstrap.css": "css/core/bootstrap-dc6f4d3c4a.css"
}ploy.css": "css/core/deploy-dc6f4d3c4a.css"
}8dd.css"
}
```

The manifest contents changes every time the task runs, sometimes it results in one correct file but most of the times it has this partial content. 

This happens regardless whether I use buffer or not.

Is there something I'm doing wrong or is there an issue?

Thanks  & regards

**Comment by gkatsanos** [comment]
+1

**Comment by danbender** [comment]
+1

**Comment by dwurster** [comment]
:+1:

**Comment by sercaninaler** [comment]
++1;

**Comment by BerkeleyTrue** [comment]
Because you are merging the resulting manifest file and you have concurrent(parallel) task running at once, in some situations this will result in two streams trying to write the file at once. 

If you instead make these separate task run in series, one after the other completes, that should solve your problem. 

Another possible solution is to remove the merge feature, give each manifest its own name, and add a new gulp task that watches the resulting files for changes, src's them, merges them, then outputs it to the desired filename.

**Comment by chrisnew** [comment]
Still have a similar issue with concurrent rev calls. Would it be possible to lock the rev file while working with it and let the other tasks wait for unlock? merge doesn't for me work, the tasks keep overwriting the manifest file mutually.

**Comment by bobthecow** [comment]
No, locking is not the right answer. Do what @BerkeleyTrue said and you should be good :)

**Comment by BerkeleyTrue** [comment]
Here is an example of how I'm accomplishing this. https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/gulpfile.js#L274

Apologies for the messy file. I went with option two because I had so many different manifest files.

Anyone out there know of packages that can build manifest files in the same fashion using the command line? At the moment we are using gulp to build these in production, but I would like to remove the need for gulp on our production servers.

**Comment by ghidinelli** [comment]
Here's my approach to solving this: https://gist.github.com/ghidinelli/e9806063ddbfa74bed7e

Generate the rev-manifest.json file manually from the files in your dist folder and make sure that runs after your parallelized styles/scripts tasks by using the run-sequence plugin.

**Comment by torifat** [comment]
@austerus Closing this issue. If you still need any assistance then reopen it please. Thanks.
