### ISSUE TITLE
access to file.revHash

### ISSUE THREAD

**Issue by agentfitz** [sindresorhus/gulp-rev#27]
"The hash of each rev'd file is stored at file.revHash. You can use this for customizing the file renaming, or for building different manifest formats."

Where does one access this file.revHash? I don't see it being used in any examples. Been pounding my head on this for quite a while. I'd be happy to update the docs once I understand what's going on.

**Comment by adrianschmidt** [comment]
Is it possible to add a prefix to the hash? In order to be able to detect directly from the filename, without looking in the manifest, if a file is revisioned or not, we would like to add someting like `cachebust-` before the hash.

Currently, since we know nothing about the hash except that it's 8 characters long, we are having trouble discerning `my-image-blahblah.png` från `my-image-<actualhash>.png`

**Comment by fairyly** [comment]
@bobthecow  I use your codes  in gulpfile.js and create hashes.json ,that format is like that{"style.css":"style.css?v=11fdcc1970"}

how can i use gulp-rev-collect to modified html pages

**Comment by atamas101** [comment]
@fairyly please check the implementation here: https://github.com/atamas101/gulp-rev-format on how you can manipulate the format for the file names, or see if the options provided there would be ok for what you need.
